<?php

/**
 * This is the model base class for the table "usuarios_perfiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsuariosPerfiles".
 *
 * Columns in table "usuarios_perfiles" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $usuario_id
 * @property integer $perfil_id
 *
 */
abstract class BaseUsuariosPerfiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuarios_perfiles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsuariosPerfiles|UsuariosPerfiles', $n);
	}

	public static function representingColumn() {
		return array(
			'perfil_id',
			'usuario_id',
		);
	}

	public function rules() {
		return array(
			array('usuario_id', 'required'),
			array('usuario_id, perfil_id', 'numerical', 'integerOnly'=>true),
			array('perfil_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('usuario_id, perfil_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'usuario_id' => null,
			'perfil_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('usuario_id', $this->usuario_id);
		$criteria->compare('perfil_id', $this->perfil_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}