<?php

/**
 * This is the model base class for the table "permisos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Permisos".
 *
 * Columns in table "permisos" available as properties of the model,
 * followed by relations of table "permisos" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $clave
 *
 * @property Perfiles[] $perfiles
 * @property OrganigramaRecursosPermisos[] $organigramaRecursosPermisoses
 * @property UsuariosRecursosPermisos[] $usuariosRecursosPermisoses
 * @property Usuarios[] $usuarioses
 */
abstract class BasePermisos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'permisos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Permisos|Permisoses', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'length', 'max'=>45),
			array('descripcion', 'length', 'max'=>250),
			array('clave', 'length', 'max'=>30),
			array('nombre, descripcion, clave', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, descripcion, clave', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'perfiles' => array(self::MANY_MANY, 'Perfiles', 'perfiles_permisos(permiso_id, perfil_id)'),
			'organigramaRecursosPermisoses' => array(self::HAS_MANY, 'OrganigramaRecursosPermisos', 'permiso_id'),
			'usuariosRecursosPermisoses' => array(self::HAS_MANY, 'UsuariosRecursosPermisos', 'permiso_id'),
			'usuarioses' => array(self::MANY_MANY, 'Usuarios', 'usuarios_permisos(permiso_id, usuario_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'perfiles' => 'PerfilesPermisos',
			'usuarioses' => 'UsuariosPermisos',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'clave' => Yii::t('app', 'Clave'),
			'perfiles' => null,
			'organigramaRecursosPermisoses' => null,
			'usuariosRecursosPermisoses' => null,
			'usuarioses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('clave', $this->clave, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}