<?php

/**
 * This is the model base class for the table "perfiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Perfiles".
 *
 * Columns in table "perfiles" available as properties of the model,
 * followed by relations of table "perfiles" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $clave
 * @property integer $perfil_de_sistema
 *
 * @property Permisos[] $permisoses
 * @property Usuarios[] $usuarioses
 */
abstract class BasePerfiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'perfiles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Perfiles|Perfiles', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('perfil_de_sistema', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>45),
			array('descripcion', 'length', 'max'=>80),
			array('clave', 'length', 'max'=>40),
			array('descripcion, clave, perfil_de_sistema', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, descripcion, clave, perfil_de_sistema', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'permisoses' => array(self::MANY_MANY, 'Permisos', 'perfiles_permisos(perfil_id, permiso_id)'),
			'usuarioses' => array(self::MANY_MANY, 'Usuarios', 'usuarios_perfiles(perfil_id, usuario_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'permisoses' => 'PerfilesPermisos',
			'usuarioses' => 'UsuariosPerfiles',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'clave' => Yii::t('app', 'Clave'),
			'perfil_de_sistema' => Yii::t('app', 'Perfil De Sistema'),
			'permisoses' => null,
			'usuarioses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('clave', $this->clave, true);
		$criteria->compare('perfil_de_sistema', $this->perfil_de_sistema);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}