<?php

/**
 * This is the model base class for the table "usuarios_permisos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsuariosPermisos".
 *
 * Columns in table "usuarios_permisos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $usuario_id
 * @property integer $permiso_id
 *
 */
abstract class BaseUsuariosPermisos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuarios_permisos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsuariosPermisos|UsuariosPermisoses', $n);
	}

	public static function representingColumn() {
		return array(
			'permiso_id',
			'usuario_id',
		);
	}

	public function rules() {
		return array(
			array('usuario_id, permiso_id', 'numerical', 'integerOnly'=>true),
			array('usuario_id, permiso_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('usuario_id, permiso_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'usuario_id' => null,
			'permiso_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('usuario_id', $this->usuario_id);
		$criteria->compare('permiso_id', $this->permiso_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}